Repository WDscholia/scholia, pull requests merged in 2020-11, with the labels that each got.

#1190 Give all sections on all Scholia pages section IDs (Issue fix #1157)
  scholia/app/templates/author.html
  scholia/app/templates/author_missing.html
  scholia/app/templates/authors.html
  scholia/app/templates/award.html
  scholia/app/templates/award_empty.html
  scholia/app/templates/award_missing.html
  scholia/app/templates/catalogue.html
  scholia/app/templates/chemical.html
  scholia/app/templates/chemical_class.html
  scholia/app/templates/chemical_element.html
  scholia/app/templates/chemical_empty.html
  scholia/app/templates/chemicals_missing.html
  scholia/app/templates/clinical_trial.html
  scholia/app/templates/clinical_trial_empty.html
  scholia/app/templates/countries.html
  scholia/app/templates/country.html
  scholia/app/templates/country_topic.html
  scholia/app/templates/disease.html
  scholia/app/templates/event.html
  scholia/app/templates/event_empty.html
  scholia/app/templates/event_series.html
  scholia/app/templates/event_series_empty.html
  scholia/app/templates/gene.html
  scholia/app/templates/lexeme.html
  scholia/app/templates/lexeme_empty.html
  scholia/app/templates/location.html
  scholia/app/templates/location_topic.html
  scholia/app/templates/organization.html
  scholia/app/templates/organization_missing.html
  scholia/app/templates/organization_topic.html
  scholia/app/templates/organizations.html
  scholia/app/templates/pathway.html
  scholia/app/templates/pathway_empty.html
  scholia/app/templates/printer.html
  scholia/app/templates/printer_empty.html
  scholia/app/templates/project.html
  scholia/app/templates/project_empty.html
  scholia/app/templates/property.html
  scholia/app/templates/protein.html
  scholia/app/templates/publisher.html
  scholia/app/templates/series.html
  scholia/app/templates/software.html
  scholia/app/templates/software_empty.html
  scholia/app/templates/sponsor.html
  scholia/app/templates/taxon.html
  scholia/app/templates/topic.html
  scholia/app/templates/topic_missing.html
  scholia/app/templates/topics.html
  scholia/app/templates/use.html
  scholia/app/templates/use_empty.html
  scholia/app/templates/venue.html
  scholia/app/templates/venue_missing.html
  scholia/app/templates/venues.html
  scholia/app/templates/work.html
  scholia/app/templates/work_empty.html
  scholia/app/templates/works.html
Labels: needs revision

#1231 Added Mastodon support to the author aspect
  scholia/app/templates/base.html
Labels: aspects, enhancement

#1241 Second round of CiTO patches
  scholia/app/templates/cito.html
  scholia/app/templates/cito_empty.html
  scholia/app/templates/venue_cito.html
  scholia/app/templates/work_cito.html
  scholia/app/views.py
Labels: P2860-cites

#1248 Use the oAuth disambiguator, per issue #1242
  scholia/app/templates/author_missing.html
  scholia/app/templates/award_missing.html
  scholia/app/templates/organization_missing.html
  scholia/app/templates/topic_missing.html
  scholia/app/templates/venue_missing.html
  scholia/app/templates/work.html
Labels: ready for merge
