Repository WDscholia/scholia, pull requests merged in 2021-08, with the labels that each got.

#1520 add covid 19 to home page fix #1071
  scholia/app/templates/index.html
Labels: ready for merge

#1464 Update 404_doi.html
  scholia/app/templates/404_doi.html
Labels: needs revision

#1505 Add links to all panels
  scholia/app/static/css/scholia.css
  scholia/app/templates/base.html
Labels: ready for review

#1497 Add links to linked to/from to curation pages (#1428)
  scholia/app/templates/base.html
Labels: ready for review

#1519 Add table of contents to all pages with >= 4 headings
  scholia/app/static/css/scholia.css
  scholia/app/templates/base.html
Labels: ready for merge

#1542 Add notice for preprints
  scholia/app/templates/work_data.sparql
Labels: ready for merge

#1584 Recognize protein complexes and proteins
  scholia/app/templates/base.html
Labels: ready for review

#1572 Update to citation.js 0.5.1 and citation-quickstatements 0.4.1
  scholia/app/static/js/citation.js
Labels: ready for review

#1543 Added detection of taxons for creating buttons
  scholia/app/templates/base.html
Labels: ready for merge, max-5-lines

#1507 Use arXiv API
  requirements.txt
  scholia/arxiv.py
Labels: ready for review

#1573 Improve search results page when no results
  scholia/app/templates/search.html
Labels: ready for review, max-5-lines

#1639 Added the language of a work
  scholia/app/templates/work_data.sparql
Labels: max-5-lines

#1611 Remove duplicate topic 1598
  .github/workflows/main.yml
Labels: bug, ready for merge, max-5-lines

#1641 Fix item in home page list
  scholia/app/templates/index.html
Labels: ready for merge, max-5-lines

#1618 Fix table of contents bug
  scholia/app/templates/base.html
Labels: ready for merge, max-5-lines

#1537 Add HTML Titles to all pages
  scholia/app/templates/404.html
  scholia/app/templates/author-index.html
  scholia/app/templates/award_empty.html
  scholia/app/templates/base.html
  scholia/app/templates/catalogue_empty.html
  scholia/app/templates/chemical-index-curation.html
  scholia/app/templates/chemical-index.html
  scholia/app/templates/chemical_class_empty.html
  scholia/app/templates/chemical_element_empty.html
  scholia/app/templates/cito_empty.html
  scholia/app/templates/clinical-trial-index.html
  scholia/app/templates/complex_empty.html
  scholia/app/templates/country_empty.html
  scholia/app/templates/dataset-index.html
  scholia/app/templates/disease_empty.html
  scholia/app/templates/event_empty.html
  scholia/app/templates/event_series_empty.html
  scholia/app/templates/gene_empty.html
  scholia/app/templates/index-statistics.html
  scholia/app/templates/lexeme_empty.html
  scholia/app/templates/location_empty.html
  scholia/app/templates/organization_empty.html
  scholia/app/templates/pathway_empty.html
  scholia/app/templates/printer-index.html
  scholia/app/templates/project_empty.html
  scholia/app/templates/protein_empty.html
  scholia/app/templates/publisher_empty.html
  scholia/app/templates/series_empty.html
  scholia/app/templates/software_empty.html
  scholia/app/templates/sponsor_empty.html
  scholia/app/templates/taxon_empty.html
  scholia/app/templates/topic_empty.html
  scholia/app/templates/use_empty.html
  scholia/app/templates/venue_empty.html
  scholia/app/templates/work_empty.html
Labels: ready for merge

#1478 Add Bioschemas by proxying Wikidata content (making Google bots happy)
  scholia/app/templates/base.html
  scholia/app/views.py
  scholia/query.py
Labels: ready for review
