Repository WDscholia/scholia, pull requests merged in 2021-11, with the labels that each got.

#1694 add period at end of final sentence in CODE_OF_CONDUCT.md.
  CODE_OF_CONDUCT.md
Labels: ready for review, max-5-lines

#1627 Add link to authors organization awards 1404
  scholia/app/templates/organization_awards.sparql
Labels: ready for merge

#1648 added missing period in scholia.js
  scholia/app/static/scholia.js
Labels: ready for merge, max-5-lines

#1684 CiTO updates
  scholia/app/templates/cito_empty_statistics.sparql
Labels: ready for merge

#1655 Add message when query fail 1646
  scholia/app/static/scholia.js
Labels: ready for merge

#1602 Add pull request template 943
  PULL_REQUEST_TEMPLATE.md
Labels: needs revision

#1698 copyedits to PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: needs rebasing

#1707 Add author score to the missing-author-items query
  scholia/app/templates/topic-curation_missing-author-items.sparql
Labels: ready for merge
