Repository WDscholia/scholia, pull requests merged in 2021-03, with the labels that each got.

#1329 Update setup.py
  setup.py
Labels: ready for review

#1325 Added ROR identifier for organizations
  scholia/app/templates/base.html
  scholia/app/templates/organization.html
Labels: ready for review

#1323 Add bioRxiv route
  scholia/app/views.py
  scholia/query.py
Labels: ready for merge

#1312 Work aspect "/export" page giving BiBTeX and CITATION.cff. Input wanted.
  scholia/app/static/js/citation.js
  scholia/app/templates/work_export.html
  scholia/app/views.py
Labels: enhancement, ready for review
