Repository WDscholia/scholia, pull requests merged in 2022-01, with the labels that each got.

#1577 Add loading animations for tables
  scholia/app/static/css/scholia.css
  scholia/app/static/scholia.js
Labels: ready for merge

#1752 Added warning if the article cites an retracted article
  scholia/app/templates/work_data.sparql
Labels: aspects, SPARQL

#1560 Mimick Scite
  scholia/app/templates/work-cito-intention.html
  scholia/app/templates/work-cito-intention_incoming.sparql
  scholia/app/templates/work-cito.html
  scholia/app/templates/work_data.sparql
  scholia/app/views.py
Labels: needs rebasing

#1608 Add image for item inline with table of contents
  scholia/app/static/css/scholia.css
  scholia/app/static/scholia.js
  scholia/app/templates/base.html
Labels: ready for review

#1561 Add curation pages for all aspects
  scholia/app/templates/author-curation.html
  scholia/app/templates/award-curation.html
  scholia/app/templates/organization-curation.html
  scholia/app/templates/q_curation.html
  scholia/app/templates/topic-curation.html
  scholia/app/templates/venue-curation.html
  scholia/app/views.py
Labels: needs rebasing

#1779 putting panels back into organization curation pages
  scholia/app/templates/organization-curation.html
Labels: max-5-lines

#1777 corrected the link from curation page to Wikidata item
  scholia/app/templates/organization-curation.html
Labels: max-5-lines

#1650 Replace select2 with bootstrap-autocomplete
  scholia/app/static/bootstrap-autocomplete.min.js
  scholia/app/static/css/scholia.css
  scholia/app/static/widgets/select2/css/select2.min.css
  scholia/app/static/widgets/select2/js/select2.min.js
  scholia/app/templates/base.html
  scholia/app/templates/index.html
  scholia/app/templates/search.html
Labels: ready for review
