Repository WDscholia/scholia, pull requests merged in 2022-10, with the labels that each got.

#2122 Fix #2116 presentations at event
  scholia/app/templates/event.html
  scholia/app/templates/event_presentations.sparql
Labels: aspects, events

#2145 Adds a chemical-element data panel
  scholia/app/templates/chemical-element.html
  scholia/app/templates/chemical-element_data.sparql
Labels: enhancement, aspects

#2149 Link works to their (in Wikidata existing) preprints in the data panel
  scholia/app/templates/work_data.sparql
Labels: enhancement

#2148 Exclude this 'preprint' field when the 'preprint of' field is
  scholia/app/templates/work_data.sparql
Labels: max-5-lines
