Repository WDscholia/scholia, pull requests merged in 2023-10, with the labels that each got.

#2302 Link to Wikidata statistics page too
  scholia/app/templates/index-statistics.html
Labels: enhancement, documentation, max-5-lines

#2299 Faster query: applied WITH/AS/WHERE to postpone looking up labels and author info
  scholia/app/templates/venue_recently-published-works.sparql
Labels: performance

#2300 Updated acks
  scholia/app/templates/about.html
Labels: enhancement, documentation

#2301 Implemented random work
  scholia/app/templates/work-index.html
  scholia/app/views.py
  scholia/query.py
Labels: enhancement

#2311 Added support for 'replies to' in the data table
  scholia/app/templates/work_data.sparql
Labels: enhancement, P2675-reply-to, P941-inspired-by

#2336 Remove unused base templates
  scholia/app/templates/about-base.html
  scholia/app/templates/author-base.html
  scholia/app/templates/award-base.html
  scholia/app/templates/cito-base.html
  scholia/app/templates/dataset-base.html
  scholia/app/templates/disease-base.html
  scholia/app/templates/gene-base.html
  scholia/app/templates/ontology-base.html
  scholia/app/templates/organization-base.html
  scholia/app/templates/pathway-base.html
  scholia/app/templates/protein-base.html
  scholia/app/templates/publisher-base.html
  scholia/app/templates/series-base.html
  scholia/app/templates/software-base.html
  scholia/app/templates/taxon-base.html
  scholia/app/templates/tools-base.html
  scholia/app/templates/topic-base.html
  scholia/app/templates/venue-base.html
  scholia/app/templates/work-base.html
Labels: needs rebasing

#2350 Gender should not be required, and reduced the amount of data passed around
  scholia/app/templates/organization_advisor-graph.sparql
Labels: max-5-lines

#2344 Update query for chemicals in a compound class
  scholia/app/templates/chemical-class_related-chemicals.sparql
Labels: bug, max-5-lines

#2365 Added a link to the matching topic page
  scholia/app/templates/chemical.html
Labels: enhancement, max-5-lines

#2364 Ensure the DOI gets linked
  scholia/app/templates/chemical_found-in-taxon.sparql
Labels: max-5-lines

#2309 Like *Label, *ChemicalStructure is a new special, expects a SMILES and will use CDK Depict (Toolforge) to visualize the chemical structure in 2D
  scholia/app/static/scholia.js
  scholia/app/templates/taxon_metabolome.sparql
Labels: enhancement, visualization

#2369 Added the WikiProject index to the menu
  scholia/app/templates/base.html
Labels: enhancement, max-5-lines
