Repository WDscholia/scholia, pull requests merged in 2023-02, with the labels that each got.

#2225 Renamed the "Related Compounds" section into "Compounds with same connectivity"
  scholia/app/templates/chemical.html
Labels: ready for merge, max-5-lines

#2241 Removed redundant @id attributes
  scholia/app/templates/chemical.html
Labels: max-5-lines

#2244 Fix/recognize retracted articles as articles
  scholia/app/templates/chemical.html
  scholia/query.py
Labels: max-5-lines

#2240 Match the column header with the description (and query)
  scholia/app/templates/protein_participates-in.sparql
Labels: max-5-lines

#2238 There are enough articles now to have a table with recent articles with explicit CiTO annotations
  scholia/app/templates/cito-index.html
  scholia/app/templates/cito-index_articles.sparql
Labels: P2860-cites

#2260 suggest to only mention sourceTaxon in the GloBI query to allow for a…
  scholia/app/templates/taxon.html
Labels: ready for merge, max-5-lines
