Repository WDscholia/scholia, pull requests merged in 2025-05, with the labels that each got.

#2639 Added the datatable footer
  scholia/app/static/scholia.js
Labels: bug, max-5-lines

#2640 Adds support for SPARQL-level configuration
  scholia/app/static/scholia.js
Labels: enhancement

#2655 Update Citation.js to 0.7.19
  scholia/scrape/openreview.py
Labels: bug
